export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const VIDEO_MODE = "VIDEO_MODE";

export const SUCCESS_NOTIFICATION = "SUCCESS_NOTIFICATION";
export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const FETCH_STREAMS_SUCCESS = "FETCH_STREAMS_SUCCESS";
export const FETCH_STREAMS_HASMORE = "FETCH_STREAMS_HASMORE";
export const FETCH_STREAMS_HASMORE_SUCCESS = "FETCH_STREAMS_HASMORE_SUCCESS";
export const FETCH_STREAMS_HASMORE_DONE = "FETCH_STREAMS_HASMORE_DONE";
export const FETCH_STREAM_SUCCESS = "FETCH_STREAM_SUCCESS";
export const EDIT_STREAM_SUCCESS = "EDIT_STREAM_SUCCESS";
export const REFETCH_ALL_STREAM_BEGIN = "REFETCH_ALL_STREAM_BEGIN";
export const REFETCH_ALL_STREAM_SUCCESS = "REFETCH_ALL_STREAM_SUCCESS";

export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESSS";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const EDIT_TAG_SUCCESS = "EDIT_TAG_SUCCESS";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
