export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const FETCH_STREAMS_SUCCESS = "FETCH_STREAMS_SUCCESS";
export const FETCH_STREAMS_HASMORE = "FETCH_STREAMS_HASMORE";
export const FETCH_STREAMS_HASMORE_SUCCESS = "FETCH_STREAMS_HASMORE_SUCCESS";
export const FETCH_STREAMS_HASMORE_DONE = "FETCH_STREAMS_HASMORE_DONE";
export const FETCH_STREAM_SUCCESS = "FETCH_STREAM_SUCCESS";

export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESSS";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const EDIT_TAG_SUCCESS = "EDIT_TAG_SUCCESS";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
