export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const FETCH_STREAM_SUCCESS = "FETCH_STREAM_SUCCESS";
export const FETCH_STREAM_HASMORE = "FETCH_STREAM_HASMORE";
export const FETCH_STREAM_HASMORE_SUCCESS = "FETCH_STREAM_HASMORE_SUCCESS";
export const FETCH_STREAM_HASMORE_DONE = "FETCH_STREAM_HASMORE_DONE";
